const API_BASE = "/api";

const API_CONSTANTS = {
  LOGIN: `${API_BASE}/user/login`,
  UPDATE_EMAIL_PASSWORD: `${API_BASE}/clients/update-email-password`,
  SIGNUP: `${API_BASE}/user/signup`,
  LOGOUT: `${API_BASE}/user/auth/logout`,
  OTP_VERIFY: `${API_BASE}/user/verify-otp`,
  OTP_RESEND: `${API_BASE}/user/resend-otp`,
  PWD_RESET: `${API_BASE}/user/request-password-reset`,
  SET_NEW_PWD: `${API_BASE}/user/reset-password`,
  EMAIL_VALIDATION: `${API_BASE}/user/validate-email`,
  GET_USER_INFO: `${API_BASE}/user/auth/me`,
  GET_ORG_INFO: `${API_BASE}/user/auth/my-org`,
  GET_USER_UPDATE: `${API_BASE}/user/auth/update-profile`,
  PUT_USER_PASSWORD: `${API_BASE}/user/auth/update-password`,
  GET_ORG_UPDATE: `${API_BASE}/user/auth/update-org-profile`,
  GET_REPORT_COUNT: `${API_BASE}/reports/count`,
  GET_ALL_REPORT: `${API_BASE}/reports`,
  GET_ALL_FAQS: `${API_BASE}/faqs`,
  DELETE_MULTIPLE_REPORT: `${API_BASE}/reports/multiple`,
  REPORTS_ADD_PATIENTS: `${API_BASE}/reports/add-patient`,
  GET_GLOBAL_SEARCH_REPORTS: `${API_BASE}/reports/search`,
  GET_ALL_PATIENTS: `${API_BASE}/clients`,
  GET_ALL_CHAT: `${API_BASE}/chats`,
  GET_ALL_PATIENTS_WITH_ID: `${API_BASE}/clients/all`,
  CLIENT_MERGE: `${API_BASE}/clients/merge`,
  INVITE_PATIENTS: `${API_BASE}/clients/create`,
  OVERTIMEDATA: `${API_BASE}/clients/overtime-report`,
  CREATE_REPORTS: `${API_BASE}/reports/text`,
  CREATE_REPORTS_DRAFT: `${API_BASE}/reports/save-draft`,
  OVERALL_PATIENTS_REPORT: `${API_BASE}/clients/overall-health`,
  DELETE_PATIENT: `${API_BASE}/clients/`,
  UPLOAD_REPORT: `${API_BASE}/reports/upload-report`,
  REPORT_ADDPATIENTS: `${API_BASE}/reports/add-patient`,
  SEND_REPORT_TO_EMR: `${API_BASE}/reports/re-process-report/`,
  UPLOAD_LATTERHEAD: `${API_BASE}/user/auth/upload-pdf-letter-head`,
  DELETE_LATTERHEAD: `${API_BASE}/user/auth/delete-pdf-letter-head`,
  DELETE_USER_PROFILE_LATTERHEAD: `${API_BASE}/user/auth/delete-user-pdf-letter-head`,
  DELETE_REPORT: `${API_BASE}/reports/`,
  DELETE_APPOINTMENT_PATIENTS: `${API_BASE}/appointments/`,
  REPORT_PROCESSING: `${API_BASE}/reports/processing-details`,
  REPORT_PRESIGNED_URL: `${API_BASE}/reports/presigned-link`,
  GENERATE_TEXT: `${API_BASE}/generate/generate-text`,
  INVITE_MEMBER: `${API_BASE}/user/invite/send`,
  ACCEPT_INVITE: `${API_BASE}/user/invite/accept`,
  GET_ALL_MEMBER: `${API_BASE}/user/invite/fetch`,
  DELETE_MEMBER: `${API_BASE}/user/invite`,
  UPDATE_USER_PERMISSION: `${API_BASE}/user/permissions`,
  DASHBOARD: `${API_BASE}/dashboard`,
  DASHBOARD_TILE: `${API_BASE}/dashboard/tile`,
  TEAMS_LOGS: `${API_BASE}/activity-logs`,
  UPLOAD_SERVICE_FILE: `${API_BASE}/services/extract-service`,
  SERVICE_APPROVED: `${API_BASE}/services/bulk-create`,
  API_KEYS: {
    API_KEY: `${API_BASE}/api-keys`,
  },
  REPORTS: {
    USER_REPORT_TYPES: `${API_BASE}/user-report-types`,
    UPDATE_USER_REPORT_TYPES: `${API_BASE}/user-report-types`,
    GET_SINGLE_REPORT_TYPE: `${API_BASE}/user-report-types/`,
    ADD_TO_PATIENT: `${API_BASE}/reports/add-to-patient`,
    CHANGE_REPORT_STATUS: `${API_BASE}/reports/change-report-status/`,
  },
  GET_ALL_ORGANIZATION: `${API_BASE}/admin/organizations`,
  GET_ALL_ORGANIZATION_APPOINTMENTS: `${API_BASE}/user/organizations-dropdown?search=`,
  GET_ALL_APPOINTMENTS_PATIENT_PORTAL: `${API_BASE}/appointments`,
  CREATE_DOCTOR_APPOINTMENT: `${API_BASE}/appointments`,
  UPDATE_ORGANIZATION: `${API_BASE}/admin/organizations`,
  UPDATE_Doctors: `${API_BASE}/admin/users`,
  UPDATE_Patients: `${API_BASE}/admin/clients`,
  GET_ORGANIZATION_DETAILS: `${API_BASE}/admin/organizations`,
  GET_Users: `${API_BASE}/admin/users`,
  GET_CLIENTS: `${API_BASE}/admin/clients`,
  GET_DOCTORS: `${API_BASE}/user/doctors-dropdown?search=&specialization=&internalRole=doctor`,
  GET_DOCTORS_APPOINTMENTS: `${API_BASE}/user/doctors-dropdown?search=&specialization=&internalRole=doctor&organizationId`,
  PATIENTS: {
    PATIENT_UPDATE: `${API_BASE}/clients/update/`,
    PATIENT_LOGIN: `${API_BASE}/patients/auth/login`,
    PATIENT_OTP_VERIFY: `${API_BASE}/patients/auth/verify-otp`,
    PATIENT_RESEND_OTP: `${API_BASE}/patients/auth/resend-otp`,
    PATIENT_UPDATE_PROFILE: `${API_BASE}/patients/auth/update-profile`,
    PATIENT_UPLOAD_REPORT: `${API_BASE}/patients/reports/upload-report`,
    PATIENT_HEALTH_SUMMARY_REQUEST: `${API_BASE}/health-summary-requests`,
    PATIENT_GET_HEALTH_SUMMARY_REQUEST: `${API_BASE}/health-summary-requests`,
    PATIENT_HEALTH_SUMMARY_REQUEST_STATUS: `${API_BASE}/health-summary-requests/`,
    SWITCH_ACCOUNT: `${API_BASE}/user/auth/switch-account`,
    NEXT_SERIAL_NUMBER: `${API_BASE}/clients/next-serial-number`,
    INDIVIDUAL_PATIENT_REPORT: `${API_BASE}/reports`,
    DOWNLOAD_PATIENT_DATA: `${API_BASE}/clients/medical-history-pdf`,
    PATIENT_CHANGE_REPORT_DATA: `${API_BASE}/clients/update-health-data`,
    PATIENT_CHANGE_REPORT_DATA_NUMBER: `${API_BASE}/clients/update-metric-data`,
    REPORT_DATA: `${API_BASE}/reports/update-health-data`,
    REPORT_DATA_NUMBER: `${API_BASE}/reports/update-metric-data`,
  },
  PAYMENTS: {
    ORGANIZATION_PAYMENTS: `${API_BASE}/organization-payments`,
    ORGANIZATION_PAYMENTS_RENEW: `${API_BASE}/organization-payments/renew`,
    CLIENT_PAYMENT: `${API_BASE}/client-payments`,
    CLIENT_PAYMENTS_RENEW: `${API_BASE}/client-payments/renew`,
  },
  CHATAI: {
    INITIATE_CHAT: `${API_BASE}/generate/initiate-chat`,
    RESUME_CHAT: `${API_BASE}/generate/resume-chat`,
    RENAME_CHAT: `${API_BASE}/generate/rename-chat`,
    GET_CHAT_DATA: `${API_BASE}/chats`,
    DELETE_CHAT: `${API_BASE}/chats`,
  },
  BILLINGS: {
    SERVICE: `${API_BASE}/services`,
    CREATE_INVOICE: `${API_BASE}/invoices`,
    GET_INVOICE: `${API_BASE}/invoices`,
    INVOICE: `${API_BASE}/invoices`,
    DELETE_SERVICE: `${API_BASE}/services/`,
    SERVICE_BILLING: `${API_BASE}/services/paginated?per_page=100&page=&search=`,
  },
  BOOKROOM: {
    SERVICE: `${API_BASE}/services`,
    CREATE_INVOICE: `${API_BASE}/invoices`,
    GET_INVOICE: `${API_BASE}/invoices`,
    INVOICE: `${API_BASE}/invoices`,
  },
  APPOINTMENTS: {
    CREATE: `${API_BASE}/appointments`,
    GET: `${API_BASE}/appointments`,
    UPDATE: `${API_BASE}/appointments/`,
    DELETE: `${API_BASE}/appointments/`,
    GET_BY_ID: `${API_BASE}/appointments/get/`,
  },
  NOTIFICATION: {
    GET_NOTIFICATION: `${API_BASE}/notifications`,
    GET_NOTIFICATION_MARK_ALL_READ: `${API_BASE}/notifications/mark-all-read`,
    GET_NOTIFICATION_MARK_READ: `${API_BASE}/notifications`,
  },
  AUTH: {
    UPDATE_CONSENT: `${API_BASE}/user/auth/update-consent`,
    VERIFY_PATIENT_PASSWORD: `${API_BASE}/patients/auth/verify-password`,
    PATIENT_SEND_OTP: `${API_BASE}/patients/auth/request-reset-password`,
    PATIENT_RESET_PWD: `${API_BASE}/patients/auth/verify-reset-otp`,
  },
  ADMIN: {
    GET_ORGANIZATION: `${API_BASE}/user/organizations-dropdown?search=`,
    GET_ADMIN_ANALYTICS: `${API_BASE}/admin/dashboard`,
    POST_BROADCAST_BULK_SEND: `${API_BASE}/broadcast/bulk-send`,
    GET_PATIENT_DATA: `${API_BASE}/admin/clients/dropdown?search=`,
    GET_DOCTOR_DATA: `${API_BASE}/admin/users/dropdown?search=`,
    GET_BROADCAST_TYPE: `${API_BASE}/broadcast-types`,
    CREATE_BROADCAST_TYPE: `${API_BASE}/broadcast-types`,
    DELETE_BROADCAST_TYPE: `${API_BASE}/broadcast-types/`,
    GET_SERVICES: `${API_BASE}/admin/services`,
    POST_SERVICES: `${API_BASE}/admin/services`,
    DELETE_SERVICES: `${API_BASE}/admin/services`,
    CREATE_ADMIN_INVOICE: `${API_BASE}/admin/invoices`,
    GET_ADMIN_INVOICE: `${API_BASE}/admin/invoices`,
    UPDATE_ADMIN_INVOICE: `${API_BASE}/admin/invoices/`,
    DELETE_ADMIN_INVOICE: `${API_BASE}/admin/invoices/`,
  },
};

export default API_CONSTANTS;
