// export const INDIVIDUAL_BASE_ROUTE = "/individual";
// export const HELTH_CARE_PROVIDER_BASE_ROUTE = "/individual";

export const ROUTES = {
  LANDING_PAGE: "/start",
  LOGIN: `/login`,
  PATIENT_LOGIN: `/patient-login`,
  SIGNUP: `/register`,
  OTP_VERIFICATION: `/otp-verification`,
  PATIENT_OTP_PASSWORD_VERIFY: `/patient-opt-password-verify`,
  PATIENT_OTP_REGISTRATION: `/patient-otp-registration`,
  RESET_PWD: `/reset-password`,
  SET_NEW_PWD: `/set-password`,
  SET_PATIENT_PWD: `/set-patient-password`,
  PAtTIENT_SEND_OTP: `/patient-send-otp`,
  SELECT_ORGANIZATION: "/select-organization",
  SET_ORGANIZATION: "/set-up-organization",
  SET_PHONEOTP: "/set-up-set_phoneotp",
  SET_UP_PATIENT: "/set-up-patient",
  COMPLETE_REGISTRATION: "/complete-registration",
  UPDATE_EMAIL_PASSWORD: "/update-email-password",
  DASHBOARD: `/`,
  TEAMMANAGEMENT: "/teams",
  HEALTHREPORT: "/reports",
  REPORT_SUMMARY: "/reports/full-report-view",
  FILE_PLOAd: "/reports/add-reports",
  CREATE_REPORT: "/reports/create-report",
  PATIENTS: "/patients",
  PATIENTS_OVERALL_HEALTH: "/patients/overall-health",
  AIOBSERVATIONS: "/AI-Observations",
  VIEW_OBSERVATION: "/View-Observation",
  MEMBER_VERIFICATION_SCREEN: "/verify-member",
  TEAMLOGES: "/teams-logs",
  PDFPREVIEW: "/pdf-preview",
  PROFILE: "/organization-profile",
  USERPROFILE: "/user-profile",
  API_KEYS: "/ApiKeys",
  Organization: "/organization",
  OrganizationDetails: "/organization-details",
  CalenderPage: "/Appointments",
  ADD_PATIENT_INFORMATION: "/add-patient-information",
  PATIENT_REQUEST: "/requests",
  PAYMENTS: "/payments",
  PAYMENT_VERIFICATION: "/payment-verifiction",
  BILLING_CREATE: "/create-invoice",
  BILLINGS: "/billings",
  // BOOKROOM: "/book-room",
  PATIENTPROFILE: "/My-Profile",
  CHATHISTORY: "/chat-history",
  DOCTOR_APPOINTMENT: "/doctor-appointment",
  ADMINANALYTICS: "/admin-analytics",
  ADMIN_INVOICE: "/admin-invoice",
  ORGBROADCAST: "/org-broadcast",
  FAQS: "/FAQs",
  ADMIN_INVOICE_CREATE: "/create-admin-invoice",
};
